<?php

namespace AppBundle\Repository;

/**
 * AttendanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class AttendanceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $academy
     */
    public function findByAcademy($academy){

        /**
         * Query in SQL "SELECT * FROM attendances LEFT JOIN workshops ON attendances.workshop_id = workshops.id WHERE workshops.academy_id = 2"
         */

        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder()
            ->select('a')
            ->from('AppBundle:Attendance', 'a')
            ->leftJoin('a.workshop', 'w')
            ->where('w.academy = :academy')
            ->orderBy('a.student')
            ->setParameter('academy', $academy);


            /*->createQuery('
            SELECT a
            FROM AppBundle:Attendance a
            LEFT JOIN AppBundle:Workshop w
            ON a.workshop = w
        ');*/

        $result = $qb->getQuery()->getResult();
        return $result;
    }
}
