<?php

namespace AppBundle\Repository;

/**
 * GradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeRepository extends \Doctrine\ORM\EntityRepository
{
    function getList(){
        return [
            'workshops' => ['Symfony introduction', 'MySQL', 'Dizainas', 'GitHub'],
            'teams' => [
                'name' => 'terminal_noobs',
                'members' => [
                    [
                        'name' => 'Mantas Narkevicius',
                        'grades' => [10, 9, 8, 10]
                    ],
                    [
                        'name' => 'Viktorija Razaite',
                        'grades' => [10, 9, 8, 10]
                    ],
                    [
                        'name' => 'Matas Minelga',
                        'grades' => [10, 9, 8, 10]
                    ]
                ]
            ]
        ];
    }
}
