# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.example:
        class: AppBundle\Service\ExampleService
        arguments: ["@doctrine.orm.entity_manager"]
    app.lectors:
        class: AppBundle\Service\LectorsService
        arguments: ["@doctrine.orm.entity_manager"]

    app.dummy:
        class: AppBundle\Service\DummyDataService
        arguments: ["@doctrine.orm.entity_manager"]

    security.authentication.customized_success_handler:
        class: AppBundle\Service\LoginSuccessHandler
        public: false
        arguments:  ["@router", "@security.authorization_checker"]
