services:

    app.shoe_factory:
        class: NFQ\DemoBundle\Service\ShoeFactory
        arguments: ["@event_dispatcher"]

    app.shoe:
        class: NFQ\DemoBundle\Service\Shoe
        factory: ["@app.shoe_factory", create]

    app.shoe_list:
        class: NFQ\DemoBundle\Service\ShoesList
        arguments: ["@event_dispatcher"]


    app.event_listener:
        class: NFQ\DemoBundle\Event\EventListener
        tags:
            - { name: kernel.event_listener, event: app.pre_create, method: makeChanges }

    app.event_subscriber:
          class: NFQ\DemoBundle\Event\EventSubscriber
          tags:
              - { name: kernel.event_subscriber}
